Update run_onchange_install-packages.zsh.tmpl

diff --git a/run_onchange_install-packages.zsh.tmpl b/run_onchange_install-packages.zsh.tmpl
--- a/run_onchange_install-packages.zsh.tmpl
+++ b/run_onchange_install-packages.zsh.tmpl
@@ -1,3 +1,10 @@
 #!/usr/bin/env zsh
 
-echo hello
+PACKAGE_MANAGER={{- .packageManager -}}
+if (( ! $+commands[$PACKAGE_MANAGER] )); then
+  echo "ERROR: Missing expected package manager '$PACKAGE_MANAGER'"
+  exit 1
+fi
+
+
+
